export const permissions = [
    {
        name: "create_an_organization_account_1",
        category: "Accounts",
        group: "Create an Organization Account",
        level: "Super Admin",
        description: "Gives uers access to create an organization account",
    },
    {
        name: "delete_an_organization_account_2",
        category: "Accounts",
        group: "Delete an Organization Account",
        level: "Super Admin",
        description: "Gives users access to delete an organization account",
    },
    {
        name: "reset_an_organization_account_3",
        category: "Accounts",
        group: "Reset an Organization Account",
        level: "Super Admin",
        description: "Gives users access to reset an organizations account",
    },
    {
        name: "setup_an_organizations_academic_profile_4",
        category: "Accounts",
        group: "Setup an Organizations Academic Profile",
        level: "Super Admin",
        description:
            "Gives users access to setup an organizations academic profile",
    },
    {
        name: "edit_an_organization_details_5",
        category: "Accounts",
        group: "Edit an Organization Details",
        level: "Super Admin",
        description: "Gives users access to edit an organizations details",
    },
    {
        name: "update_default_thumbnails_6",
        category: "Accounts",
        group: "Update Default Thumbnails",
        level: "Super Admin",
        description: "Gives users access to update default thumbnails",
    },
    {
        name: "upgrade_organization_publishing_permissions_7",
        category: "Accounts",
        group: "Upgrade Organization Publishing Permissions",
        level: "Super Admin",
        description:
            "Gives users access to upgrade organization publishing permissions",
    },
    {
        name: "approve_and_reject_pending_content_8",
        category: "Accounts",
        group: "Approve and Reject Pending Content",
        level: "Super Admin",
        description: "Gives users access to approve and reject pending content",
    },
    {
        name: "create_program_category_9",
        category: "Accounts",
        group: "Create Program Category",
        level: "Super Admin",
        description: "Gives users access to create a program category",
    },
    {
        name: "change_an_organizations_visibility_settings_10",
        category: "Accounts",
        group: "Change an Organizations Visibility Settings",
        level: "Super Admin",
        description:
            "Gives users access to change an organizations visbility settings",
    },
    {
        name: "view_organization_bill_details_11",
        category: "Accounts",
        group: "View Organization Bill Details",
        level: "Super Admin",
        description: "Gives users access to view organization bill details",
    },
    {
        name: "block_org_users_access_12",
        category: "Accounts",
        group: "Block Org Users Access",
        level: "Super Admin",
        description: "Gives users access to block organization users access",
    },
    {
        name: "create_pricing_plan_13",
        category: "Accounts",
        group: "Create Pricing Plan",
        level: "Super Admin",
        description: "Gives users access to create a pricing plan",
    },
    {
        name: "logos_1000",
        category: "Accounts",
        group: "Logos",
        level: "Org Admin",
        description: "Gives users access to view logos",
    },
    {
        name: "my_account_1010",
        category: "Accounts",
        group: "My Account",
        level: "Org Admin",
        description: "Gives users access to view my account",
    },
    {
        name: "my_settings_1020",
        category: "Accounts",
        group: "My Settings",
        level: "Teacher",
        description: "Gives users access to edit their settings",
    },
    {
        name: "personalizations_1030",
        category: "Accounts",
        group: "Personalizations",
        level: "Teacher",
        description: "Gives users access to view personalizations",
    },
    {
        name: "my_learners_page_1040",
        category: "Accounts",
        group: "My Learners Page",
        level: "School Admin",
        description: "Gives users access to view my learners page",
    },
    {
        name: "my_learners_dashboards_1041",
        category: "Accounts",
        group: "My Learners Dashboards",
        level: "School Admin",
        description: "Gives users access to view my learners dashboards",
    },
    {
        name: "my_learners_schedule_1042",
        category: "Accounts",
        group: "My Learners Schedule",
        level: "School Admin",
        description: "Gives users access to view my learners schedule",
    },
    {
        name: "my_learners_study_plan_1043",
        category: "Accounts",
        group: "My Learners Study Plan",
        level: "School Admin",
        description: "Gives users access to view my learners study plan",
    },
    {
        name: "my_learners_notifications_1044",
        category: "Accounts",
        group: "My Learners Notifications",
        level: "School Admin",
        description: "Gives users access to view my learners notifications",
    },
    {
        name: "my_learners_make_a_payment_1045",
        category: "Accounts",
        group: "My Learners Make A Payment",
        level: "School Admin",
        description: "Gives users access to view my learners make a payment",
    },
    {
        name: "my_learners_coupon_management_1046",
        category: "Accounts",
        group: "My Learners Coupon Management",
        level: "School Admin",
        description: "Gives users access to view my learners coupon management",
    },
    {
        name: "my_learners_view_promotions_1047",
        category: "Accounts",
        group: "My Learners View Promotions",
        level: "School Admin",
        description: "Gives users access to view my learners view promotions",
    },
    {
        name: "my_learners_class_recordings_1048",
        category: "Accounts",
        group: "My Learners Class Recordings",
        level: "School Admin",
        description: "Gives users access to view my learners class recordings",
    },
    {
        name: "my_learners_attendance_report_1049",
        category: "Accounts",
        group: "My Learners Attendance Report",
        level: "Teacher",
        description: "Gives users access to view my learners attendance report",
    },
    {
        name: "live_100",
        category: "Live",
        group: "Live",
        level: "School Admin",
        description: "",
    },
    {
        name: "go_live_101",
        category: "Live",
        group: "Go Live",
        level: "School Admin",
        description: "Gives users access to go live",
    },
    {
        name: "view_organization_live_recordings_110",
        category: "Accounts",
        group: "View Organization Live Recordings",
        level: "Org Admin",
        description: "Gives users access to view organization live recordings",
    },
    {
        name: "manage_live_classroom_recording_120",
        category: "Accounts",
        group: "Manage Live Classroom Recording",
        level: "Org Admin",
        description: "Gives users access to manage live classroom recordings",
    },
    {
        name: "override_live_classroom_recording_130",
        category: "Accounts",
        group: "Override Live Classroom Recording",
        level: "Org Admin",
        description: "Gives users access to override live classroom recordings",
    },
    {
        name: "delete_live_classroom_recordings_140",
        category: "Accounts",
        group: "Delete Live Classroom Recordings",
        level: "Org Admin",
        description: "Gives users access to delete live classroom recordings",
    },
    {
        name: "live_default_interface_170",
        category: "Live",
        group: "Live Default Interface",
        level: "Operational",
        description: "",
    },
    {
        name: "auto_interface_based_on_age_range_171",
        category: "Live",
        group: "Auto Interface based on Age Range",
        level: "Org Admin",
        description: "Gives users access to auto interface based on age range",
    },
    {
        name: "record_live_classes_172",
        category: "Accounts",
        group: "Record Live Classes",
        level: "Teacher",
        description: "Gives users acces to record live classes",
    },
    {
        name: "record_class_classes_173",
        category: "Accounts",
        group: "Record Class Classes",
        level: "Teacher",
        description: "Gives users access to record class classes",
    },
    {
        name: "collaboration_show_web_cam_dynamic_174",
        category: "Accounts",
        group: "Collaboration Show Web Cam Dynamic",
        level: "Teacher",
        description: "",
    },
    {
        name: "collaboration_show_web_cam_focus_175",
        category: "Accounts",
        group: "Collaboration Show Web Cam Focus",
        level: "Teacher",
        description: "",
    },
    {
        name: "collaboration_teacher_present_176",
        category: "Accounts",
        group: "Collaboration Teacher Present",
        level: "Teacher",
        description: "",
    },
    {
        name: "collaboration_observe_mode_177",
        category: "Accounts",
        group: "Collaboration Observe Mode",
        level: "Teacher",
        description: "",
    },
    {
        name: "collaboration_screenshare_mode_178",
        category: "Accounts",
        group: "Collaboration Screenshare Mode",
        level: "Teacher",
        description: "",
    },
    {
        name: "participants_tab_179",
        category: "Accounts",
        group: "Participants Tab",
        level: "Teacher",
        description: "",
    },
    {
        name: "lesson_plan_tab_180",
        category: "Accounts",
        group: "Lesson Plan Tab",
        level: "Teacher",
        description: "",
    },
    {
        name: "teaches_desk_tab_181",
        category: "Accounts",
        group: "Teaches Desk Tab",
        level: "Teacher",
        description: "",
    },
    {
        name: "settings_tab_182",
        category: "Accounts",
        group: "Settings Tab",
        level: "Teacher",
        description: "",
    },
    {
        name: "view_lesson_attachments_183",
        category: "Accounts",
        group: "View Lesson Attachments",
        level: "Teacher",
        description: "Gives users access to view lesson attachments",
    },
    {
        name: "view_starred_content_184",
        category: "Accounts",
        group: "View Starred Content",
        level: "Teacher",
        description: "Gives users access to view starred content",
    },
    {
        name: "see_recommended_content_based_on_age_range_185",
        category: "Accounts",
        group: "See Recommended Content based on Age Range",
        level: "Teacher",
        description:
            "Gives users access to see recommended content based on age range",
    },
    {
        name: "attend_live_class_as_a_teacher_186",
        category: "Accounts",
        group: "Attend Live Class as a Teacher",
        level: "Teacher",
        description: "Gives users access to attend live class as a teacher",
    },
    {
        name: "attend_live_class_as_a_student_187",
        category: "Accounts",
        group: "Attend Live Class as a Student",
        level: "Teacher",
        description: "Gives users access to attend live class as a student",
    },
    {
        name: "library_200",
        category: "Library",
        group: "Library",
        level: "Org Admin",
        description: "",
    },
    {
        name: "create_content_page_201",
        category: "Library",
        group: "Create Content Page",
        level: "Org Admin",
        description: "Gives users access to create content pages",
    },
    {
        name: "unpublished_content_page_202",
        category: "Library",
        group: "Unpublished Content Page",
        level: "Org Admin",
        description: "Gives users access to view unpublished content pages",
    },
    {
        name: "pending_content_page_203",
        category: "Library",
        group: "Pending Content Page",
        level: "Org Admin",
        description: "Gives users access to view pending content pages",
    },
    {
        name: "published_content_page_204",
        category: "Library",
        group: "Published Content Page",
        level: "Org Admin",
        description: "Gives users access to view published content pages",
    },
    {
        name: "archived_content_page_205",
        category: "Library",
        group: "Archived Content Page",
        level: "Org Admin",
        description: "Gives users access to view archived content pages",
    },
    {
        name: "view_asset_db_300",
        category: "Library",
        group: "View Asset DB",
        level: "Org Admin",
        description: "Gives users access to view asset database",
    },
    {
        name: "view_my_unpublished_content_210",
        category: "Library",
        group: "View My Unpublished Content",
        level: "Org Admin",
        description: "Gives users access to view my unpublished content",
    },
    {
        name: "view_org_unpublished_content_211",
        category: "Library",
        group: "View Org Unpublished Content",
        level: "Org Admin",
        description: "Gives users access to view org unpublished content",
    },
    {
        name: "view_my_pending_212",
        category: "Library",
        group: "View My Pending",
        level: "Org Admin",
        description: "Gives users access to view my pending",
    },
    {
        name: "view_org_pending_213",
        category: "Library",
        group: "View Org Pending",
        level: "Org Admin",
        description: "Gives users access to view org pending",
    },
    {
        name: "view_my_published_214",
        category: "Library",
        group: "View My Published",
        level: "Org Admin",
        description: "Gives users access to view my published",
    },
    {
        name: "view_org_published_215",
        category: "Library",
        group: "View Org Published",
        level: "Org Admin",
        description: "Gives users access to view org published",
    },
    {
        name: "view_my_archived_216",
        category: "Library",
        group: "View My Archived",
        level: "Org Admin",
        description: "Gives users access to view my archived",
    },
    {
        name: "view_org_archived_217",
        category: "Library",
        group: "View Org Archived",
        level: "Org Admin",
        description: "Gives users access to view org archived",
    },
    {
        name: "view_my_school_published_218",
        category: "Accounts",
        group: "View My School Published",
        level: "School Admin",
        description: "Gives users access to view my school published",
    },
    {
        name: "view_my_school_pending_225",
        category: "Accounts",
        group: "View My School Pending",
        level: "School Admin",
        description: "Gives users access to view my school pending",
    },
    {
        name: "view_my_school_archived_226",
        category: "Accounts",
        group: "View My School Archived",
        level: "School Admin",
        description: "Gives users access to view my school archived",
    },
    {
        name: "view_all_schools_published_227",
        category: "Accounts",
        group: "View All Schools Published",
        level: "Org Admin",
        description: "Gives users access to view all schools published",
    },
    {
        name: "view_all_schools_pending_228",
        category: "Accounts",
        group: "View All Schools Pending",
        level: "Org Admin",
        description: "Gives users access to view all schools pending",
    },
    {
        name: "view_all_schools_archived_229",
        category: "Accounts",
        group: "View All Schools Archived",
        level: "Org Admin",
        description: "Gives users access to view all schools archived",
    },
    {
        name: "create_lesson_material_220",
        category: "Accounts",
        group: "Create Lesson Material",
        level: "",
        description: "Gives users access to create lesson material",
    },
    {
        name: "create_lesson_plan_221",
        category: "Accounts",
        group: "Create Lesson Plan",
        level: "Org Admin",
        description: "Gives users access to create lesson plans",
    },
    {
        name: "copy_content_222",
        category: "Accounts",
        group: "Copy Content",
        level: "",
        description: "Gives users access to copy content",
    },
    {
        name: "create_my_schools_content_223",
        category: "Accounts",
        group: "Create My Schools Content",
        level: "School Admin",
        description: "Gives users access to create my schools content",
    },
    {
        name: "create_all_schools_content_224",
        category: "Accounts",
        group: "Create All Schools Content",
        level: "Org Admin",
        description: "Gives users access to create all schools content",
    },
    {
        name: "edit_my_unpublished_content_230",
        category: "Accounts",
        group: "Edit My Unpublished Content",
        level: "Teacher",
        description: "Gives users access to edit my unpublished content",
    },
    {
        name: "edit_org_unpublished_content_231",
        category: "Accounts",
        group: "Edit Org Unpublished Content",
        level: "Teacher",
        description: "Gives users access to edit my org unpublished ontent",
    },
    {
        name: "edit_my_pending_content_232",
        category: "Accounts",
        group: "Edit My Pending Content",
        level: "Teacher",
        description: "Gives users access to edit my pending content",
    },
    {
        name: "edit_org_pending_content_233",
        category: "Accounts",
        group: "Edit Org Pending Content",
        level: "Org Admin",
        description: "Gives users access to edit org pending content",
    },
    {
        name: "edit_my_published_content_234",
        category: "Accounts",
        group: "Edit My Published Content",
        level: "Org Admin",
        description: "Gives users access to edit my published content",
    },
    {
        name: "edit_org_published_content_235",
        category: "Accounts",
        group: "Edit Org Published Content",
        level: "Org Admin",
        description: "Gives users access to edit org published content",
    },
    {
        name: "edit_lesson_material_metadata_and_content_236",
        category: "Accounts",
        group: "Edit Lesson Material Metadata and Content",
        level: "Org Admin",
        description:
            "Gives users access to edit lesson material metadata and content",
    },
    {
        name: "edit_lesson_plan_metadata_237",
        category: "Accounts",
        group: "Edit Lesson Plan Metadata",
        level: "Org Admin",
        description: "Gives users access to edit lesson plan metadata",
    },
    {
        name: "edit_lesson_plan_content_238",
        category: "Accounts",
        group: "Edit Lesson Plan Content",
        level: "Org Admin",
        description: "Gives users access to edit lesson plan content",
    },
    {
        name: "download_lesson_plan_239",
        category: "Accounts",
        group: "Download Lesson Plan",
        level: "Org Admin",
        description: "Gives users access to download lesson plan",
    },
    {
        name: "edit_my_schools_published_247",
        category: "Library",
        group: "Edit My Schools Published",
        level: "School Admin",
        description: "Gives users access to edit my schools published",
    },
    {
        name: "edit_my_schools_pending_248",
        category: "Library",
        group: "Edit My Schools Pending",
        level: "School Admin",
        description: "Gives users access to my schools pending",
    },
    {
        name: "edit_all_schools_published_249",
        category: "Library",
        group: "Edit All Schools Published",
        level: "Org Admin",
        description: "Gives users access to edit all schools published",
    },
    {
        name: "edit_all_schools_pending_250",
        category: "Library",
        group: "Edit All Schools Pending",
        level: "Org Admin",
        description: "Gives users access to edit all schools pending",
    },
    {
        name: "delete_my_unpublished_content_240",
        category: "Library",
        group: "Delete My Unpublished Content",
        level: "Org Admin",
        description: "Gives users access to delete my unpublished content",
    },
    {
        name: "delete_my_schools_pending_241",
        category: "Library",
        group: "Delete My Schools Pending",
        level: "Teacher",
        description: "Gives users access to delete my schools pending",
    },
    {
        name: "remove_my_schools_published_242",
        category: "Library",
        group: "Remove My Schools Published",
        level: "Teacher",
        description: "Gives users access to remove my schools published",
    },
    {
        name: "delete_my_schools_archived_243",
        category: "Library",
        group: "Delete My Schools Archived",
        level: "Teacher",
        description: "Gives users access to delete my schools archived",
    },
    {
        name: "delete_all_schools_pending_244",
        category: "Library",
        group: "Delete All Schools Pending",
        level: "Org Admin",
        description: "Gives users access to delete all schools pending",
    },
    {
        name: "remove_all_schools_published_245",
        category: "Library",
        group: "Remove All Schools Published",
        level: "Org Admin",
        description: "Gives users access to remove all schools published",
    },
    {
        name: "delete_all_schools_archived_246",
        category: "Library",
        group: "Delete All Schools Archived",
        level: "Org Admin",
        description: "Gives users access to delete all schools archived",
    },
    {
        name: "library_settings_270",
        category: "Library",
        group: "Library Settings",
        level: "Operational",
        description: "Gives users access to library settings",
    },
    {
        name: "approve_pending_content_271",
        category: "Library",
        group: "Approve Pending Content",
        level: "Org Admin",
        description: "Gives users access to approve pending content",
    },
    {
        name: "reject_pending_content_272",
        category: "Library",
        group: "Reject Pending Content",
        level: "Org Admin",
        description: "Gives users access to reject pending content",
    },
    {
        name: "archive_published_content_273",
        category: "Library",
        group: "Archive Published Content",
        level: "Org Admin",
        description: "Gives users access to archive published content",
    },
    {
        name: "republish_archived_content_274",
        category: "Library",
        group: "Republish Archived Content",
        level: "Org Admin",
        description: "Gives users access to republish archived content",
    },
    {
        name: "delete_archived_content_275",
        category: "Library",
        group: "Delete Archived Content",
        level: "Org Admin",
        description: "Gives users access to delete archived content",
    },
    {
        name: "details_upload_thumbnail_276",
        category: "Library",
        group: "Details Upload Thumbnail",
        level: "Org Admin",
        description: "",
    },
    {
        name: "details_manually_add_program_277",
        category: "",
        group: "Details Manually Add Program",
        level: "Org Admin",
        description: "",
    },
    {
        name: "details_manually_add_developmental_skill_278",
        category: "",
        group: "Details Manually Add Developmental Skill",
        level: "Org Admin",
        description: "",
    },
    {
        name: "details_manually_add_skills_category_279",
        category: "",
        group: "Details Manually Add Skills Category",
        level: "Org Admin",
        description: "",
    },
    {
        name: "details_manually_add_suitable_age_280",
        category: "Library",
        group: "Details Manually Add Suitable Age",
        level: "Org Admin",
        description: "",
    },
    {
        name: "details_manually_add_grade_281",
        category: "Library",
        group: "Details Manually Add Grade",
        level: "Org Admin",
        description: "",
    },
    {
        name: "share_content_282",
        category: "",
        group: "Share Content",
        level: "Org Admin",
        description: "Gives users access to share content",
    },
    {
        name: "favorite_content_283",
        category: "",
        group: "Favorite Content",
        level: "Org Admin",
        description: "Gives users access to favorite content",
    },
    {
        name: "associate_learning_outcomes_284",
        category: "",
        group: "Associate Learning Outcomes",
        level: "Org Admin",
        description: "Gives users access to associate learning outcomes",
    },
    {
        name: "publish_featured_content_with_lo_285",
        category: "",
        group: "Publish Featured Content with LO",
        level: "Org Admin",
        description: "Gives users access to publish featured content with LO",
    },
    {
        name: "publish_featured_content_no_lo_286",
        category: "",
        group: "Publish Featured Content no LO",
        level: "Org Admin",
        description:
            "Gives users access to publish featured content with no LO",
    },
    {
        name: "publish_free_content_with_lo_287",
        category: "",
        group: "Publish Free Content with LO",
        level: "Org Admin",
        description: "Gives users access to publish free content with LO",
    },
    {
        name: "publish_free_content_no_lo_288",
        category: "",
        group: "Publish Free Content no LO",
        level: "Org Admin",
        description: "Gives users access to publish free content with no LO",
    },
    {
        name: "asset_db_300",
        category: "Library",
        group: "Asset DB",
        level: "Org Admin",
        description: "",
    },
    {
        name: "create_asset_page_301",
        category: "Library",
        group: "Create Asset Page",
        level: "Org Admin",
        description: "Gives users access to create asset pages",
    },
    {
        name: "view_asset_310",
        category: "Library",
        group: "View Asset",
        level: "Org Admin",
        description: "Gives users access to view asset",
    },
    {
        name: "view_live_recordings_311",
        category: "",
        group: "View Live Recordings",
        level: "Org Admin",
        description: "Gives users access to view live recordings",
    },
    {
        name: "create_asset_320",
        category: "Library",
        group: "Create Asset",
        level: "Org Admin",
        description: "Gives users access to create asset pages",
    },
    {
        name: "upload_asset_321",
        category: "Library",
        group: "Upload Asset",
        level: "Org Admin",
        description: "Gives users access to upload assets",
    },
    {
        name: "edit_asset_330",
        category: "Library",
        group: "Edit Asset",
        level: "Org Admin",
        description: "Gives users access to edit assets",
    },
    {
        name: "download_asset_331",
        category: "Library",
        group: "Download Asset",
        level: "Org Admin",
        description: "Gives users access to download assets",
    },
    {
        name: "delete_asset_340",
        category: "Library",
        group: "Delete Asset",
        level: "Org Admin",
        description: "Gives users access to delete assets",
    },
    {
        name: "asset_db_settings_380",
        category: "Library",
        group: "Asset DB Settings",
        level: "Org Admin",
        description: "Gives users access to asset DB settings",
    },
    {
        name: "assessments_400",
        category: "Assessments",
        group: "Assessments",
        level: "Org Admin",
        description: "Gives users access to assessments",
    },
    {
        name: "create_learning_outcome_page_401",
        category: "Assessments",
        group: "Create Learning Outcome Page",
        level: "Org Admin",
        description: "Gives users access to create learning outcome pages",
    },
    {
        name: "unpublished_page_402",
        category: "Assessments",
        group: "Unpublished Page",
        level: "Org Admin",
        description: "Gives users access to view unpublished pages",
    },
    {
        name: "pending_page_403",
        category: "Assessments",
        group: "Pending Page",
        level: "Org Admin",
        description: "Gives users access to view pending pages",
    },
    {
        name: "learning_outcome_page_404",
        category: "Assessments",
        group: "Learning Outcome Page",
        level: "Org Admin",
        description: "Gives users access to view learning outcome pages",
    },
    {
        name: "milestones_page_405",
        category: "Assessments",
        group: "Milestones Page",
        level: "Org Admin",
        description: "Gives users access to view milestones pages",
    },
    {
        name: "assessments_page_406",
        category: "Assessments",
        group: "Assessments Page",
        level: "Org Admin",
        description: "Gives users access to view assessments pages",
    },
    {
        name: "view_my_unpublished_learning_outcome_410",
        category: "Assessments",
        group: "View My Unpublished Learning Outcome",
        level: "Org Admin",
        description:
            "Gives users access to view my unpublished learning outcomes",
    },
    {
        name: "view_org_unpublished_learning_outcome_411",
        category: "Assessments",
        group: "View Org Unpublished Learning Outcome",
        level: "Org Admin",
        description:
            "Gives users access to view org unpublished learning outcomes",
    },
    {
        name: "view_my_pending_learning_outcome_412",
        category: "Assessments",
        group: "View My Pending Learning Outcome",
        level: "Org Admin",
        description: "Gives users access to view my pending learning outcomes",
    },
    {
        name: "view_org_pending_learning_outcome_413",
        category: "Assessments",
        group: "View Org Pending Learning Outcome",
        level: "Org Admin",
        description: "Gives users access to view org pending learning outcomes",
    },
    {
        name: "view_completed_assessments_414",
        category: "Assessments",
        group: "View Completed Assessments",
        level: "Org Admin",
        description: "Gives users access to view completed assessments",
    },
    {
        name: "view_in_progress_assessments_415",
        category: "Assessments",
        group: "View In Progress Assessments",
        level: "Org Admin",
        description: "Gives users access to view in progress assessments",
    },
    {
        name: "view_published_learning_outcome_416",
        category: "Assessments",
        group: "View Published Learning Outcome",
        level: "Org Admin",
        description: "Gives users access to view published learning outcome",
    },
    {
        name: "view_unpublished_milestone_417",
        category: "Assessments",
        group: "View Unpublished Milestone",
        level: "Org Admin",
        description: "Gives users access to view unpublished milestone",
    },
    {
        name: "view_published_milestone_418",
        category: "Assessments",
        group: "View Published Milestone",
        level: "Org Admin",
        description: "Gives users access to view published milestones",
    },
    {
        name: "view_unpublished_standard_419",
        category: "",
        group: "View Unpublished Standard",
        level: "Org Admin",
        description: "Gives users access to view the unpublished standard",
    },
    {
        name: "view_published_standard_420",
        category: "",
        group: "View Published Standard",
        level: "Org Admin",
        description: "Gives users access to view the published standard",
    },
    {
        name: "view_org_completed_assessments_424",
        category: "Assessments",
        group: "View Org Completed Assessments",
        level: "Org Admin",
        description: "Gives users access to create learning outcomes",
    },
    {
        name: "view_org_in_progress_assessments_425",
        category: "Assessments",
        group: "View Org In Progress Assessments",
        level: "Org Admin",
        description: "Gives users access to create milestones",
    },
    {
        name: "view_school_completed_assessments_426",
        category: "Assessments",
        group: "View School Completed Assessments",
        level: "Org Admin",
        description: "Gives users access to create standards",
    },
    {
        name: "view_school_in_progress_assessments_427",
        category: "Assessments",
        group: "View School In Progress Assessments",
        level: "",
        description:
            "Gives users access to edit my unpublished learning outcomes",
    },
    {
        name: "create_learning_outcome_421",
        category: "Assessments",
        group: "Create Learning Outcome",
        level: "Org Admin",
        description:
            "Gives users access to edit org unpublished learning outcomes",
    },
    {
        name: "create_milestone_422",
        category: "Assessments",
        group: "Create Milestone",
        level: "Org Admin",
        description:
            "Gives users access to remove content from the learning outcomes cart",
    },
    {
        name: "create_standard_423",
        category: "Assessments",
        group: "Create Standard",
        level: "Org Admin",
        description: "Gives users access to add content learning outcomes",
    },
    {
        name: "edit_my_unpublished_learning_outcome_430",
        category: "Assessments",
        group: "Edit My Unpublished Learning Outcome",
        level: "Org Admin",
        description: "Gives users access to edit my pending learning outcomes",
    },
    {
        name: "edit_org_unpublished_learning_outcome_431",
        category: "Assessments",
        group: "Edit Org Unpublished Learning Outcome",
        level: "Org Admin",
        description: "Gives users access to edit org pending learning outcomes",
    },
    {
        name: "remove_content_learning_outcomes_cart_432",
        category: "Assessments",
        group: "Remove Content Learning Outcomes Cart",
        level: "Org Admin",
        description:
            "Gives users access to remove content learning outcomes from the cart",
    },
    {
        name: "add_content_learning_outcomes_433",
        category: "Assessments",
        group: "Add Content Learning Outcomes",
        level: "Org Admin",
        description: "Gives users access to add content learning outcomes",
    },
    {
        name: "edit_my_pending_learning_outcome_434",
        category: "Assessments",
        group: "Edit My Pending Learning Outcome",
        level: "Org Admin",
        description: "Gives users access to edit my pending learning outcomes",
    },
    {
        name: "edit_org_pending_learning_outcome_435",
        category: "Assessments",
        group: "Edit Org Pending Learning Outcome",
        level: "Org Admin",
        description: "Gives users access to edit org pending learning outcomes",
    },
    {
        name: "edit_published_learning_outcome_436",
        category: "Assessments",
        group: "Edit Published Learning Outcome",
        level: "Org Admin",
        description: "Gives users access to edit published learning outcomes",
    },
    {
        name: "edit_attendance_for_completed_assessment_437",
        category: "Assessments",
        group: "Edit Attendance for Completed Assessment",
        level: "Super Admin",
        description:
            "Gives users access to edit attendance for completed assessmens",
    },
    {
        name: "edit_attendance_for_in_progress_assessment_438",
        category: "Assessments",
        group: "Edit Attendance for In Progress Assessment",
        level: "Org Admin",
        description:
            "Gives users access to edit attendance for in progress assessments",
    },
    {
        name: "edit_in_progress_assessment_439",
        category: "Assessments",
        group: "Edit In Progress Assessment",
        level: "Org Admin",
        description: "Gives users access to edit in progress assessments",
    },
    {
        name: "edit_unpublished_milestone_440",
        category: "Assessments",
        group: "Edit Unpublished Milestone",
        level: "Org Admin",
        description: "Gives users access to edit unpublished milestones",
    },
    {
        name: "edit_published_milestone_441",
        category: "Assessments",
        group: "Edit Published Milestone",
        level: "Org Admin",
        description: "Gives users access to edit published milestones",
    },
    {
        name: "edit_unpublished_standard_442",
        category: "",
        group: "Edit Unpublished Standard",
        level: "Org Admin",
        description: "Gives users access to edit unpublished standards",
    },
    {
        name: "edit_published_standard_443",
        category: "",
        group: "Edit Published Standard",
        level: "Org Admin",
        description: "Gives users access to edit published standards",
    },
    {
        name: "delete_my_unpublished_learninng_outcome_444",
        category: "Assessments",
        group: "Delete My Unpublished Learninng Outcome",
        level: "Org Admin",
        description:
            "Gives users access to delete my unpublished learning outcomes",
    },
    {
        name: "delete_org_unpublished_learning_outcome_445",
        category: "Assessments",
        group: "Delete Org Unpublished Learning Outcome",
        level: "Org Admin",
        description:
            "Gives users access to delete org unpublished learning outcomes",
    },
    {
        name: "delete_my_pending_learning_outcome_446",
        category: "Assessments",
        group: "Delete My Pending Learning Outcome",
        level: "Org Admin",
        description:
            "Gives users access to delete my pending learning outcomes",
    },
    {
        name: "delete_org_pending_learning_outcome_447",
        category: "Assessments",
        group: "Delete Org Pending Learning Outcome",
        level: "Org Admin",
        description:
            "Gives users access to delete org pending learning outcomes",
    },
    {
        name: "delete_published_learning_outcome_448",
        category: "Assessments",
        group: "Delete Published Learning Outcome",
        level: "Org Admin",
        description: "Gives users access to delete published learning outcomes",
    },
    {
        name: "delete_unpublish_milestone_449",
        category: "Assessments",
        group: "Delete Unpublish Milestone",
        level: "Org Admin",
        description: "Gives users access to delete unpublished milestones",
    },
    {
        name: "delete_published_milestone_450",
        category: "Assessments",
        group: "Delete Published Milestone",
        level: "Org Admin",
        description: "Gives users access to delete published milestones",
    },
    {
        name: "delete_unpublished_standard_451",
        category: "Assessments",
        group: "Delete Unpublished Standard",
        level: "Org Admin",
        description: "Gives users access to delete unpublished standards",
    },
    {
        name: "delete_published_standard_452",
        category: "Assessments",
        group: "Delete Published Standard",
        level: "Org Admin",
        description: "Gives users access to delete published standards",
    },
    {
        name: "assessment_settings_480",
        category: "Assessments",
        group: "Assessment Settings",
        level: "Org Admin",
        description: "Gives users access to view assessment settings",
    },
    {
        name: "approve_pending_learning_outcome_481",
        category: "Assessments",
        group: "Approve Pending Learning Outcome",
        level: "Org Admin",
        description: "Gives users access to approve pending learning outcomes",
    },
    {
        name: "reject_pending_learning_outcome_482",
        category: "Assessments",
        group: "Reject Pending Learning Outcome",
        level: "Org Admin",
        description: "Gives users access to reject pending learning outcomes",
    },
    {
        name: "upload_learning_outcomes_483",
        category: "Assessments",
        group: "Upload Learning Outcomes",
        level: "Org Admin",
        description: "Gives users access to upload learning outcomes",
    },
    {
        name: "download_learning_outcomes_484",
        category: "Assessments",
        group: "Download Learning Outcomes",
        level: "Org Admin",
        description: "Gives users access to download learning outcomes",
    },
    {
        name: "add_learning_outcome_to_content_485",
        category: "Assessments",
        group: "Add Learning Outcome to Content",
        level: "Org Admin",
        description: "Gives users access to add learning outcomes to content",
    },
    {
        name: "schedule_500",
        category: "Schedule",
        group: "Schedule",
        level: "Org Admin",
        description: "Gives users access to view schedules",
    },
    {
        name: "create_schedule_page_501",
        category: "Schedule",
        group: "Create Schedule Page",
        level: "Org Admin",
        description: "Gives users access to create schedule pages",
    },
    {
        name: "view_my_calendar_510",
        category: "Schedule",
        group: "View My Calendar",
        level: "Org Admin",
        description: "Gives users access to view my calendar",
    },
    {
        name: "view_org_calendar_511",
        category: "Schedule",
        group: "View Org Calendar",
        level: "Org Admin",
        description: "Gives users access to view org calendar",
    },
    {
        name: "view_school_calendar_512",
        category: "Schedule",
        group: "View School Calendar",
        level: "Org Admin",
        description: "Gives users access to view school calendar",
    },
    {
        name: "create_event_520",
        category: "Schedule",
        group: "Create Event",
        level: "Org Admin",
        description: "Gives users access to create events",
    },
    {
        name: "edit_event_530",
        category: "Schedule",
        group: "Edit Event",
        level: "Org Admin",
        description: "Gives users access to edit events",
    },
    {
        name: "override_live_classroom_recording_setting_531",
        category: "Schedule",
        group: "Override Live Classroom Recording Setting",
        level: "Org Admin",
        description:
            "Gives users access to override live classroom recording settings",
    },
    {
        name: "delete_event_540",
        category: "Schedule",
        group: "Delete Event",
        level: "Org Admin",
        description: "Gives users access to delete events",
    },
    {
        name: "schedule_settings_580",
        category: "Schedule",
        group: "Schedule Settings",
        level: "Org Admin",
        description: "Gives users access to schedule settings",
    },
    {
        name: "schedule_quick_start_581",
        category: "Schedule",
        group: "Schedule Quick Start",
        level: "Org Admin",
        description: "Gives users access to schedule quick starts",
    },
    {
        name: "schedule_search_582",
        category: "Schedule",
        group: "Schedule Search",
        level: "Org Admin",
        description: "Gives users access to schedule searches",
    },
    {
        name: "reports_600",
        category: "Reports",
        group: "Reports",
        level: "Org Admin",
        description: "",
    },
    {
        name: "org_reports_601",
        category: "Reports",
        group: "Org Reports",
        level: "Org Admin",
        description: "Gives users access to view org reports",
    },
    {
        name: "school_reports_602",
        category: "Reports",
        group: "School Reports",
        level: "Org Admin",
        description: "Gives users access to view school reports",
    },
    {
        name: "teacher_reports_603",
        category: "Reports",
        group: "Teacher Reports",
        level: "Org Admin",
        description: "Gives users access to view teacher reports",
    },
    {
        name: "class_reports_604",
        category: "Reports",
        group: "Class Reports",
        level: "Org Admin",
        description: "Gives users access to vew class reports",
    },
    {
        name: "student_reports_605",
        category: "Reports",
        group: "Student Reports",
        level: "Org Admin",
        description: "Gives users access to vew student reports",
    },
    { name: "", category: "", group: "", level: "", description: "" },
    { name: "", category: "", group: "", level: "", description: "" },
    {
        name: "view_reports_610",
        category: "Reports",
        group: "View Reports",
        level: "Org Admin",
        description: "Gives users access to view reports",
    },
    {
        name: "view_my_school_reports_611",
        category: "Reports",
        group: "View My School Reports",
        level: "Org Admin",
        description: "Gives users access to view my school reports",
    },
    {
        name: "view_my_organizations_reports_612",
        category: "Reports",
        group: "View My Organizations Reports",
        level: "Org Admin",
        description: "Gives users access to view my organization reports",
    },
    {
        name: "view_all_organizations_reports_613",
        category: "Reports",
        group: "View All Organizations Reports",
        level: "Super Admin",
        description: "Gives users access to view all organization reports",
    },
    {
        name: "view_my_reports_614",
        category: "Reports",
        group: "View My Reports",
        level: "Teacher",
        description: "Gives users access to view my reports",
    },
    {
        name: "report_student_achievement_615",
        category: "Reports",
        group: "Report Student Achievement",
        level: "Org Admin",
        description: "Gives users access to report student achievement",
    },
    {
        name: "report_learning_outcomes_in_categories_616",
        category: "Reports",
        group: "Report Learning Outcomes in Categories",
        level: "Org Admin",
        description:
            "Gives users access to report learning outcomes in categories",
    },
    {
        name: "share_report_630",
        category: "Report",
        group: "Share Report",
        level: "Org Admin",
        description: "Gives users access to share reports",
    },
    {
        name: "download_report_631",
        category: "Report",
        group: "Download Report",
        level: "Org Admin",
        description: "Gives users access to download reports",
    },
    {
        name: "report_settings_680",
        category: "Report",
        group: "Report Settings",
        level: "Org Admin",
        description: "Gives users access to report settings",
    },
    {
        name: "organizational_profile_10100",
        category: "General",
        group: "Organizational Profile",
        level: "Org Admin",
        description: "",
    },
    {
        name: "view_all_organization_details_page_10101",
        category: "General",
        group: "View All Organization Details Page",
        level: "Org Admin",
        description: "Gives users access to view all organization details page",
    },
    {
        name: "view_this_organization_profile_10110",
        category: "General",
        group: "View This Organization Profile",
        level: "Org Admin",
        description: "Gives users access to view this organization profile",
    },
    {
        name: "view_my_organization_profile_10111",
        category: "General",
        group: "View My Organization Profile",
        level: "Org Admin",
        description: "Gives users access to view my organization profile",
    },
    {
        name: "view_organization_details_10112",
        category: "General",
        group: "View Organization Details",
        level: "Org Admin",
        description: "Gives users access to view organization details",
    },
    {
        name: "create_own_organization_10220",
        category: "General",
        group: "Create Own Organization",
        level: "Parent",
        description: "Gives users access to create their own organization",
    },
    {
        name: "edit_this_organization_10330",
        category: "General",
        group: "Edit This Organization",
        level: "Org Admin",
        description: "Gives users access to edit this organization",
    },
    {
        name: "edit_my_organization_10331",
        category: "General",
        group: "Edit My Organization",
        level: "Org Admin",
        description: "Gives users access to edit my organization",
    },
    {
        name: "edit_email_address_10332",
        category: "General",
        group: "Edit Email Address",
        level: "Org Admin",
        description: "Gives users access to edit their email address",
    },
    {
        name: "edit_password_10333",
        category: "General",
        group: "Edit Password",
        level: "Org Admin",
        description: "Gives users access to edit their password",
    },
    {
        name: "delete_organization_10440",
        category: "General",
        group: "Delete Organization",
        level: "Org Admin",
        description: "Gives users access to delete an organization",
    },
    {
        name: "change_owner_10880",
        category: "General",
        group: "Change Owner",
        level: "Org Admin",
        description: "Gives users access to change owners",
    },
    {
        name: "join_organization_10881",
        category: "General",
        group: "Join Organization",
        level: "Org Admin",
        description: "Gives users access to join an organization",
    },
    {
        name: "leave_organization_10882",
        category: "General",
        group: "Leave Organization",
        level: "Org Admin",
        description: "Gives users access to leave an organization",
    },
    {
        name: "school_resources_20100",
        category: "General",
        group: "School Resources",
        level: "Org Admin",
        description: "Gives users access to view school resources",
    },
    {
        name: "define_school_program_page_20101",
        category: "General",
        group: "Define School Program Page",
        level: "Org Admin",
        description: "Gives users access to define school program pages",
    },
    {
        name: "define_age_ranges_page_20102",
        category: "General",
        group: "Define Age Ranges Page",
        level: "Org Admin",
        description: "Gives users access to define age ranges page",
    },
    {
        name: "define_grade_page_20103",
        category: "General",
        group: "Define Grade Page",
        level: "Org Admin",
        description: "Gives users access to define grade page",
    },
    {
        name: "view_school_20110",
        category: "General",
        group: "View School",
        level: "Org Admin",
        description: "Gives users access to view school",
    },
    {
        name: "view_program_20111",
        category: "General",
        group: "View Program",
        level: "Org Admin",
        description: "Gives users access to view program",
    },
    {
        name: "view_age_range_20112",
        category: "General",
        group: "View Age Range",
        level: "Org Admin",
        description: "Gives users access to view age range",
    },
    {
        name: "view_grades_20113",
        category: "General",
        group: "View Grades",
        level: "Org Admin",
        description: "Gives users access to view grades",
    },
    {
        name: "view_classes_20114",
        category: "General",
        group: "View Classes",
        level: "Org Admin",
        description: "Gives users access to view classes",
    },
    {
        name: "create_school_20220",
        category: "General",
        group: "Create School",
        level: "Org Admin",
        description: "Gives users access to create schools",
    },
    {
        name: "create_program_20221",
        category: "General",
        group: "Create Program",
        level: "Org Admin",
        description: "Gives users access to create programs",
    },
    {
        name: "create_age_range_20222",
        category: "General",
        group: "Create Age Range",
        level: "Org Admin",
        description: "Gives users access to create age ranges",
    },
    {
        name: "create_grade_20223",
        category: "General",
        group: "Create Grade",
        level: "Org Admin",
        description: "Gives users access to create grades",
    },
    {
        name: "create_class_20224",
        category: "General",
        group: "Create Class",
        level: "Org Admin",
        description: "Gives users access to create classes",
    },
    {
        name: "add_students_to_class_20225",
        category: "General",
        group: "Add Students to Class",
        level: "Org Admin",
        description: "Gives users access to add students to class",
    },
    {
        name: "add_teachers_to_class_20226",
        category: "General",
        group: "Add Teachers to Class",
        level: "Org Admin",
        description: "Gives users access to add teachers to class",
    },
    {
        name: "edit_school_20330",
        category: "General",
        group: "Edit School",
        level: "Org Admin",
        description: "Gives users access to edit school",
    },
    {
        name: "edit_program_20331",
        category: "General",
        group: "Edit Program",
        level: "Org Admin",
        description: "Gives users access to edit programs",
    },
    {
        name: "edit_age_range_20332",
        category: "General",
        group: "Edit Age Range",
        level: "Org Admin",
        description: "Gives users access to edit age range",
    },
    {
        name: "edit_grade_20333",
        category: "General",
        group: "Edit Grade",
        level: "Org Admin",
        description: "Gives users access to edit grades",
    },
    {
        name: "edit_class_20334",
        category: "General",
        group: "Edit Class",
        level: "Org Admin",
        description: "Gives users access to edit class",
    },
    {
        name: "move_students_to_another_class_20335",
        category: "General",
        group: "Move Students to Another Class",
        level: "Org Admin",
        description: "Gives users access to move students to another class",
    },
    {
        name: "edit_teacher_in_class_20336",
        category: "General",
        group: "Edit Teacher in Class",
        level: "Org Admin",
        description: "Gives users access to edit teacher in class",
    },
    {
        name: "delete_school_20440",
        category: "General",
        group: "Delete School",
        level: "Org Admin",
        description: "Gives users access to delete schools",
    },
    {
        name: "delete_program_20441",
        category: "General",
        group: "Delete Program",
        level: "Org Admin",
        description: "Gives users access to delete programs",
    },
    {
        name: "delete_age_range_20442",
        category: "General",
        group: "Delete Age Range",
        level: "Org Admin",
        description: "Gives users access to delete age ranges",
    },
    {
        name: "delete_grade_20443",
        category: "General",
        group: "Delete Grade",
        level: "Org Admin",
        description: "Gives users access to delete grades",
    },
    {
        name: "delete_class_20444",
        category: "General",
        group: "Delete Class",
        level: "Org Admin",
        description: "Gives users access to delete classes",
    },
    {
        name: "delete_student_from_class_roster_20445",
        category: "General",
        group: "Delete Student from Class Roster",
        level: "Org Admin",
        description: "Gives users access to delete students from class rosters",
    },
    {
        name: "delete_teacher_from_class_20446",
        category: "General",
        group: "Delete Teacher from Class",
        level: "Org Admin",
        description: "Gives users access to delete teachers from class",
    },
    {
        name: "upload_schools_20880",
        category: "General",
        group: "Upload Schools",
        level: "Org Admin",
        description: "Gives users access to upload schools",
    },
    {
        name: "download_schools_20881",
        category: "General",
        group: "Download Schools",
        level: "Org Admin",
        description: "Gives users access to download schools",
    },
    {
        name: "upload_program_20882",
        category: "General",
        group: "Upload Program",
        level: "Org Admin",
        description: "Gives users access to upload programs",
    },
    {
        name: "download_program_20883",
        category: "General",
        group: "Download Program",
        level: "Org Admin",
        description: "Gives users access to download programs",
    },
    {
        name: "upload_class_roster_with_teachers_20884",
        category: "General",
        group: "Upload Class Roster with Teachers",
        level: "Org Admin",
        description: "Gives users access to upload class rosters with teachers",
    },
    {
        name: "download_class_roster_with_teachers_20885",
        category: "General",
        group: "Download Class Roster with Teachers",
        level: "Org Admin",
        description:
            "Gives users access to download class rosters with teachers",
    },
    {
        name: "upload_age_range_20886",
        category: "General",
        group: "Upload Age Range",
        level: "Org Admin",
        description: "Gives users access to upload age ranges",
    },
    {
        name: "download_age_range_20887",
        category: "General",
        group: "Download Age Range",
        level: "Org Admin",
        description: "Gives users access to download age ranges",
    },
    {
        name: "upload_grades_20888",
        category: "General",
        group: "Upload Grades",
        level: "Org Admin",
        description: "Gives users access to upload grades",
    },
    {
        name: "download_grades_20889",
        category: "General",
        group: "Download Grades",
        level: "Org Admin",
        description: "Gives users access to download grades",
    },
    {
        name: "upload_classes_20890",
        category: "General",
        group: "Upload Classes",
        level: "Org Admin",
        description: "Gives users access to upload classes",
    },
    {
        name: "download_classes_20891",
        category: "General",
        group: "Download Classes",
        level: "Org Admin",
        description: "Gives users access to download classes",
    },
    {
        name: "groups_30100",
        category: "",
        group: "Groups",
        level: "Org Admin",
        description: "",
    },
    {
        name: "role_levels_30101",
        category: "",
        group: "Role Levels",
        level: "Org Admin",
        description: "Gives users access to view role levels",
    },
    {
        name: "permissions_30102",
        category: "",
        group: "Permissions",
        level: "Org Admin",
        description: "Gives users access to view permissions",
    },
    {
        name: "view_groups_30110",
        category: "",
        group: "View Groups",
        level: "Org Admin",
        description: "Gives users access to view groups",
    },
    {
        name: "view_role_priority_levels_30111",
        category: "",
        group: "View Role Priority Levels",
        level: "Org Admin",
        description: "Gives users access to view role priority levels",
    },
    {
        name: "view_role_permissions_30112",
        category: "",
        group: "View Role Permissions",
        level: "Org Admin",
        description: "Gives users access to view role permissions",
    },
    {
        name: "create_groups_30220",
        category: "",
        group: "Create Groups",
        level: "Org Admin",
        description: "Gives users access to create groups",
    },
    {
        name: "create_role_priority_levels_30221",
        category: "",
        group: "Create Role Priority Levels",
        level: "Org Admin",
        description: "Gives users access to create role priority levels",
    },
    {
        name: "create_role_with_permissions_30222",
        category: "",
        group: "Create Role with Permissions",
        level: "Org Admin",
        description: "Gives users access to create roles with permissions",
    },
    {
        name: "edit_groups_30330",
        category: "",
        group: "Edit Groups",
        level: "Org Admin",
        description: "Gives users access to edit groups",
    },
    {
        name: "edit_role_priority_levels_30331",
        category: "",
        group: "Edit Role Priority Levels",
        level: "Org Admin",
        description: "Gives users access to edit role priority levels",
    },
    {
        name: "edit_role_permissions_30332",
        category: "",
        group: "Edit Role Permissions",
        level: "Org Admin",
        description: "Gives users access to edit role permissions",
    },
    {
        name: "delete_groups_30440",
        category: "",
        group: "Delete Groups",
        level: "Org Admin",
        description: "Gives users access to delete groups",
    },
    {
        name: "users_40100",
        category: "General",
        group: "Users",
        level: "Org Admin",
        description: "",
    },
    {
        name: "view_user_page_40101",
        category: "General",
        group: "View User Page",
        level: "Org Admin",
        description: "Gives users access to view user pages",
    },
    {
        name: "view_users_40110",
        category: "General",
        group: "View Users",
        level: "Org Admin",
        description: "Gives users access to view users",
    },
    {
        name: "create_users_40220",
        category: "General",
        group: "Create Users",
        level: "Org Admin",
        description: "Gives users access to create users",
    },
    {
        name: "edit_users_40330",
        category: "General",
        group: "Edit Users",
        level: "Org Admin",
        description: "Gives users access to edit users",
    },
    {
        name: "delete_users_40440",
        category: "General",
        group: "Delete Users",
        level: "Org Admin",
        description: "Gives users access to delete users",
    },
    {
        name: "upload_users_40880",
        category: "General",
        group: "Upload Users",
        level: "Org Admin",
        description: "Gives users access to upload users",
    },
    {
        name: "download_users_40881",
        category: "General",
        group: "Download Users",
        level: "Org Admin",
        description: "Gives users access to download users",
    },
    {
        name: "send_invitation_40882",
        category: "General",
        group: "Send Invitation",
        level: "Org Admin",
        description: "Gives users access to send invitations",
    },
    {
        name: "deactivate_user_40883",
        category: "General",
        group: "Deactivate User",
        level: "Org Admin",
        description: "Gives users access to deactivate users",
    },
    {
        name: "billing_50100",
        category: "General",
        group: "Billing",
        level: "Org Admin",
        description: "",
    },
    {
        name: "view_payment_details_and_make_payment_50101",
        category: "General",
        group: "View Payment Details and Make Payment",
        level: "Org Admin",
        description:
            "Gives users access to view payment details and make payments",
    },
    {
        name: "view_billing_details_50110",
        category: "General",
        group: "View Billing Details",
        level: "Org Admin",
        description: "Gives users access to view billing details",
    },
    {
        name: "purchase_more_minutes_50880",
        category: "General",
        group: "Purchase More Minutes",
        level: "Org Admin",
        description: "Gives users access to purchase more minutes",
    },
    {
        name: "purchase_more_storage_50881",
        category: "General",
        group: "Purchase More Storage",
        level: "Org Admin",
        description: "Gives users access to purchase more storage",
    },
    {
        name: "purchase_next_plan_50882",
        category: "General",
        group: "Purchase Next Plan",
        level: "Org Admin",
        description: "Gives users access to purchase the next plan",
    },
    {
        name: "download_billing_50883",
        category: "General",
        group: "Download Billing",
        level: "Org Admin",
        description: "Gives users access to download billing",
    },
    {
        name: "support_60100",
        category: "General",
        group: "Support",
        level: "Org Admin",
        description: "",
    },
    {
        name: "online_support_60101",
        category: "General",
        group: "Online Support",
        level: "Org Admin",
        description: "Gives users access to view online support",
    },
    {
        name: "featured_programs_70000",
        category: "Live",
        group: "Featured Programs",
        level: "Org Admin",
        description: "",
    },
    {
        name: "view_any_featured_programs_70001",
        category: "Live",
        group: "View Any Featured Programs",
        level: "Org Admin",
        description: "Gives users access to view any featured programs",
    },
    {
        name: "bada_rhyme_71000",
        category: "Live",
        group: "Bada Rhyme",
        level: "Org Admin",
        description: "Gives users access to view Bada Rhyme",
    },
    {
        name: "bada_genius_71001",
        category: "Live",
        group: "Bada Genius",
        level: "Org Admin",
        description: "Gives users access to view Bada Genius",
    },
    {
        name: "bada_talk_71002",
        category: "Live",
        group: "Bada Talk",
        level: "Org Admin",
        description: "Gives users access to view Bada Talk",
    },
    {
        name: "bada_sound_71003",
        category: "Live",
        group: "Bada Sound",
        level: "Org Admin",
        description: "Gives users access to view Bada Sound",
    },
    {
        name: "bada_read_71004",
        category: "Live",
        group: "Bada Read",
        level: "Org Admin",
        description: "Gives users access to view Bada Read",
    },
    {
        name: "bada_math_71005",
        category: "Live",
        group: "Bada Math",
        level: "Org Admin",
        description: "Gives users access to view Bada Math",
    },
    {
        name: "bada_stem_71006",
        category: "Live",
        group: "Bada STEM",
        level: "Org Admin",
        description: "Gives users access to view Bada STEM",
    },
    {
        name: "badanamu_esl_71007",
        category: "Live",
        group: "Badanamu ESL",
        level: "Org Admin",
        description: "Gives users access to view Badanamu ESL",
    },
    {
        name: "undefined_71008",
        category: "",
        group: "undefined",
        level: "",
        description: "undefined",
    },
    {
        name: "undefined_71009",
        category: "",
        group: "undefined",
        level: "",
        description: "undefined",
    },
    {
        name: "bada_rhyme_75000",
        category: "Live",
        group: "Bada Rhyme",
        level: "Org Admin",
        description: "Gives users access to create Bada Rhyme",
    },
    {
        name: "bada_genius_75001",
        category: "Live",
        group: "Bada Genius",
        level: "Org Admin",
        description: "Gives users access to create Bada Genius",
    },
    {
        name: "bada_talk_75002",
        category: "Live",
        group: "Bada Talk",
        level: "Org Admin",
        description: "Gives users access to create Bada Talk",
    },
    {
        name: "bada_sound_75003",
        category: "Live",
        group: "Bada Sound",
        level: "Org Admin",
        description: "Gives users access to create Bada Sound",
    },
    {
        name: "bada_read_75004",
        category: "Live",
        group: "Bada Read",
        level: "Org Admin",
        description: "Gives users access to create Bada Read",
    },
    {
        name: "bada_math_75005",
        category: "Live",
        group: "Bada Math",
        level: "Org Admin",
        description: "Gives users access to create Bada Math",
    },
    {
        name: "bada_stem_75006",
        category: "Live",
        group: "Bada STEM",
        level: "Org Admin",
        description: "Gives users access to create Bada STEM",
    },
    {
        name: "badanamu_esl_75007",
        category: "Live",
        group: "Badanamu ESL",
        level: "Org Admin",
        description: "Gives users access to create Badanamu ESL ",
    },
    {
        name: "undefined_75008",
        category: "",
        group: "undefined",
        level: "",
        description: "undefined",
    },
    {
        name: "undefined_75009",
        category: "",
        group: "undefined",
        level: "",
        description: "undefined",
    },
    {
        name: "bada_rhyme_78000",
        category: "Live",
        group: "Bada Rhyme",
        level: "Org Admin",
        description: "Gives users access to edit Bada Rhyme",
    },
    {
        name: "bada_genius_78001",
        category: "Live",
        group: "Bada Genius",
        level: "Org Admin",
        description: "Gives users access to edit Bada Genius",
    },
    {
        name: "bada_talk_78002",
        category: "Live",
        group: "Bada Talk",
        level: "Org Admin",
        description: "Gives users access to edit Bada Talk",
    },
    {
        name: "bada_sound_78003",
        category: "Live",
        group: "Bada Sound",
        level: "Org Admin",
        description: "Gives users access to edit Bada Sound",
    },
    {
        name: "bada_read_78004",
        category: "Live",
        group: "Bada Read",
        level: "Org Admin",
        description: "Gives users access to edit Bada Read",
    },
    {
        name: "bada_math_78005",
        category: "Live",
        group: "Bada Math",
        level: "Org Admin",
        description: "Gives users access to edit Bada Math",
    },
    {
        name: "bada_stem_78006",
        category: "Live",
        group: "Bada STEM",
        level: "Org Admin",
        description: "Gives users access to edit Bada STEM",
    },
    {
        name: "badanamu_esl_78007",
        category: "Live",
        group: "Badanamu ESL",
        level: "Org Admin",
        description: "Gives users access to edit Badanamu ESL",
    },
    {
        name: "undefined_78008",
        category: "",
        group: "undefined",
        level: "",
        description: "undefined",
    },
    {
        name: "unndefined_78009",
        category: "",
        group: "unndefined",
        level: "",
        description: "undefined",
    },
    {
        name: "publish_featured_content_for_all_hub_79000",
        category: "",
        group: "Publish featured content for all hub",
        level: "",
        description:
            "Gives users access to publish featured content for all hub",
    },
    {
        name: "publish_featured_content_for_specific_orgs_79001",
        category: "",
        group: "Publish featured content for specific orgs",
        level: "",
        description:
            "Gives users access to publish featured content for specific organizations",
    },
    {
        name: "publish_featured_content_for_all_orgs_79002",
        category: "",
        group: "Publish featured content for all orgs",
        level: "",
        description:
            "Gives users access to publish featured content for all organizations",
    },
    {
        name: "free_programs_80000",
        category: "",
        group: "Free Programs",
        level: "",
        description: "",
    },
    {
        name: "view_free_programs_80001",
        category: "",
        group: "View Free Programs",
        level: "",
        description: "Gives users access to view free programs",
    },
    {
        name: "bada_rhyme_81000",
        category: "Library",
        group: "Bada Rhyme",
        level: "Org Admin",
        description: "Gives users access to view Bada Rhyme",
    },
    {
        name: "bada_genius_81001",
        category: "Library",
        group: "Bada Genius",
        level: "Org Admin",
        description: "Gives users access to view Bada Genius",
    },
    {
        name: "bada_talk_81002",
        category: "Library",
        group: "Bada Talk",
        level: "Org Admin",
        description: "Gives users access to view Bada Talk",
    },
    {
        name: "bada_sound_81003",
        category: "Library",
        group: "Bada Sound",
        level: "Org Admin",
        description: "Gives users access to view Bada Sound",
    },
    {
        name: "bada_read_81004",
        category: "Library",
        group: "Bada Read",
        level: "Org Admin",
        description: "Gives users access to view Bada Read",
    },
    {
        name: "bada_math_81005",
        category: "Library",
        group: "Bada Math",
        level: "Org Admin",
        description: "Gives users access to view Bada Math",
    },
    {
        name: "bada_stem_81006",
        category: "Library",
        group: "Bada STEM",
        level: "Org Admin",
        description: "Gives users access to view Bada STEM",
    },
    {
        name: "badanamu_esl_81007",
        category: "Library",
        group: "Badanamu ESL",
        level: "Org Admin",
        description: "Gives users access to view Badanamu ESL",
    },
    {
        name: "use_free_as_recommended_content_for_study_81008",
        category: "",
        group: "Use Free as Recommended Content for Study",
        level: "Org Admin",
        description:
            "Gives users access to use free as recommended content for study",
    },
    {
        name: "undefinend_81009",
        category: "",
        group: "undefinend",
        level: "",
        description: "undefined",
    },
    {
        name: "bada_rhyme_85000",
        category: "Library",
        group: "Bada Rhyme",
        level: "Super Admin",
        description: "Gives users access to create Bada Rhyme",
    },
    {
        name: "bada_genius_85001",
        category: "Library",
        group: "Bada Genius",
        level: "Super Admin",
        description: "Gives users access to create Bada Genius",
    },
    {
        name: "bada_talk_85002",
        category: "Library",
        group: "Bada Talk",
        level: "Super Admin",
        description: "Gives users access to create Bada Talk",
    },
    {
        name: "bada_sound_85003",
        category: "Library",
        group: "Bada Sound",
        level: "Super Admin",
        description: "Gives users access to create Bada Sound",
    },
    {
        name: "bada_read_85004",
        category: "Library",
        group: "Bada Read",
        level: "Super Admin",
        description: "Gives users access to create Bada Read",
    },
    {
        name: "bada_math_75005",
        category: "Library",
        group: "Bada Math",
        level: "Super Admin",
        description: "Gives users access to create Bada Math",
    },
    {
        name: "bada_stem_75006",
        category: "Library",
        group: "Bada STEM",
        level: "Super Admin",
        description: "Gives users access to create Bada STEM",
    },
    {
        name: "undefined_75007",
        category: "",
        group: "undefined",
        level: "",
        description: "undefined",
    },
    {
        name: "undefined_75008",
        category: "",
        group: "undefined",
        level: "",
        description: "undefined",
    },
    {
        name: "unndefined_75009",
        category: "",
        group: "unndefined",
        level: "",
        description: "undefined",
    },
    {
        name: "bada_rhyme_78000",
        category: "Library",
        group: "Bada Rhyme",
        level: "Super Admin",
        description: "Gives users access to edit Bada Rhyme",
    },
    {
        name: "bada_genius_78001",
        category: "Library",
        group: "Bada Genius",
        level: "Super Admin",
        description: "Gives users access to edit Bada Genius",
    },
    {
        name: "bada_talk_78002",
        category: "Library",
        group: "Bada Talk",
        level: "Super Admin",
        description: "Gives users access to edit Bada Talk",
    },
    {
        name: "bada_sound_78003",
        category: "Library",
        group: "Bada Sound",
        level: "Super Admin",
        description: "Gives users access to edit Bada Sound",
    },
    {
        name: "bada_read_78004",
        category: "Library",
        group: "Bada Read",
        level: "Super Admin",
        description: "Gives users access to edit Bada Read",
    },
    {
        name: "bada_math_78005",
        category: "Library",
        group: "Bada Math",
        level: "Super Admin",
        description: "Gives users access to edit Bada Math",
    },
    {
        name: "bada_stem_78006",
        category: "Library",
        group: "Bada STEM",
        level: "Super Admin",
        description: "Gives users access to edit Bada STEM",
    },
    {
        name: "badanamu_esl_78007",
        category: "Library",
        group: "Badanamu ESL",
        level: "Super Admin",
        description: "Gives users access to edit Badanamu ESL",
    },
    {
        name: "undefined_78008",
        category: "",
        group: "undefined",
        level: "",
        description: "undefined",
    },
    {
        name: "unndefined_78009",
        category: "",
        group: "unndefined",
        level: "",
        description: "undefined",
    },
    {
        name: "publish_free_content_for_all_hub_79000",
        category: "Library",
        group: "Publish free content for all hub",
        level: "Super Admin",
        description: "Gives users access to publish free content for all hub",
    },
    {
        name: "publish_free_content_for_specific_orgs_79001",
        category: "Library",
        group: "Publish free content for specific orgs",
        level: "Super Admin",
        description:
            "Gives users access to publish free content for specific organizations",
    },
    {
        name: "publish_free_content_for_all_orgs_79002",
        category: "Library",
        group: "Publish free content for all orgs",
        level: "Super Admin",
        description:
            "Gives users access to publish frree content for all organizations",
    },
];
